---
name: lab-02
break: true
indent: 4
---
src/main:
    java:
        poem/DisplayPoem.java:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 0 --exact
            CountMultipleLineComments --language Java --count 2
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
            MatchFileRegex --regex "println\(" --count 10
        
writing:
    reflection.md:
        ConfirmFileExists
        CountFileWords --count 250
        CountMarkdownTags --tag "heading" --count 3
        MatchFileFragment --fragment "TODO" --count 0 --exact
        
CountCommits --count 2
CountCommandOutput --command "gradle -q --console plain run" --count 10